version: '3'
services:
  graphdom:
    build: .
    tty: true
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      REDIS_URL: redis://redis:6379
      SERVER_PORT: 8080
    command: yarn start
    volumes:
      - ./:/graphdom
      - /graphdom/node_modules # Exclude node_modules
    ports:
      - 8080:8080

  redis:
    image: redis:5.0.7
    restart: unless-stopped
    ports:
      - 6379:6379
