service:
  name: aws-lambda-puppeteer
frameworkVersion: ">=1.50.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: false
    packager: yarn
  serverless-offline:
    port: 8080
  puppeteer:
    executablePath:
      local: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'local'}
  region: ${opt:region,'ap-northeast-1'}
  iamRoleStatements:
  environment:

layers:
  nodeModules:
    path: layers
    package:
      include:
        - node_modules/**
    compatibleRuntimes:
      - nodejs8.10
    licenseInfo: Apache-2.0
    allowedAccounts:
      - "*"
    retain: false

functions:
  hello:
    handler: src/index.handler
    memorySize: 128MB
    timeout: 180
    events:
      - http:
          method: get
          path: /hello
    environment:
      PUPPETEER_EXECUTABLE_PATH: ${self:custom.puppeteer.executablePath.${self:provider.stage},''}
    layers:
      - {Ref: NodeModulesLambdaLayer}

resources:
  Resources:
  Outputs:
