aliases:
  - &install-dependencies
    name: Intall all dependencies
    command: yarn install --ignore-optional --frozen-lockfile
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - v2-dependencies-{{ .Branch }}-
  - &save-cache
    paths:
      - node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/node:12
    working_directory: ~/graph-dom
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-dependencies
      - save_cache: *save-cache
      - run:
          name: Check code format & run lint
          command: yarn lint
          no_output_timeout: 1m

  license:
    docker:
      - image: circleci/node:12
    working_directory: ~/graph-dom
    steps:
      - checkout
      - run:
          name: Install fossa-cli
          command: |
            curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
          no_output_timeout: 5m
      - run:
          name: Check yarn dependency licenses
          command: fossa test -c .fossa/config.yml
          no_output_timeout: 1m

  test:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/graph-dom
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-dependencies
      - save_cache: *save-cache
      - run:
          name: Run unit tests
          command: yarn test:unit --ci
          no_output_timeout: 5m
      - store_test_results:
          path: ./reports/test
      - store_artifacts:
          path: ./reports/test
          destination: jest
      - store_artifacts:
          path: ./reports/coverage/lcov-report
          destination: lcov

  e2e:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/graph-dom
    environment:
      NODE_ENV: development
      GRAPH_DOM_BROWSER_HEADLESS: true
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-dependencies
      - save_cache: *save-cache
      - run:
          name: Run E2E tests
          command: yarn test:e2e --ci --runInBand
          no_output_timeout: 5m
      - store_test_results:
          path: ./reports/test
      - store_artifacts:
          path: ./reports/test
          destination: jest

  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/graph-dom
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-dependencies
      - save_cache: *save-cache
      - run:
          name: Build app
          command: yarn build
          no_output_timeout: 5m

  deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/graph-dom
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install-dependencies
      - save_cache: *save-cache
      - deploy:
          name: Deploy to ZEIT
          command: yarn deploy --token $ZEIT_TOKEN
          no_output_timeout: 5m
      - run:
          name: Publish schema to Apollo
          command: yarn apollo:publish --endpoint=https://graph-dom.t28.now.sh/graphql --tag=production
          no_output_timeout: 5m

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - master
      - license:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - lint
      - build:
          requires:
            - license
            - lint
            - test
      - e2e:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - e2e
            - build
          filters:
            branches:
              only:
                - master
