version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    default_assignees:
      - "t28hub"
